### ISSUE TITLE
QWidget: Cannot create a QWidget without QApplication

### ISSUE THREAD

**Issue by vishnucool220** [ncp1402/ql-lineplot#1]
Hi,
I followed all your steps and addition to it i have added to my pro file. 
MAKE_CXXFLAGS += -std=c++11
QT += qml quick
QT += widgets
QT += printsupport
but still it says QWidget: Cannot create a QWidget without QApplication. Any idea where i went wrong? Thanks

**Comment by vishnucool220** [comment]
I changed QGuiApplication in main.cpp to QApplication.Then it worked but i want to work with QGuiApplication. Please tell me how can i do that.Thanks

**Comment by ncp1402** [comment]
QApplication inherits QGuiApplication.

**Comment by vishnucool220** [comment]
so you mean to say that the problem is not with QApplication? If so any idea what might be causing " Qwdiget cannot create a Qwidget without QApplications" ? 
P.S: Did you test with Qt5.4 using QGuiApplication? Thanks a lot

**Comment by ncp1402** [comment]
try to use QApplication instead of QGuiApplication

**Comment by vishnucool220** [comment]
Its works with QApplication but the application i have developed so far is using QguiApplication. when i replace in my project it is creating problem. That's y i am requesting you is there any other way to draw graph?

**Comment by ncp1402** [comment]
qcustomplot based on QWidget.
QGuiApplication do not support QWidget, so qcustomplot object can't be used in QGuiApplication.

**Comment by vishnucool220** [comment]
okay bad luck for me :(

**Comment by vishnucool220** [comment]
hai,
I some how made it work with QApplicatoin thanks for your help. If you don't mind can you please give me an example where i can push the data at run time. for example i get the data from Cpp side throught a signal to QML side now how can i apped the data and plot it for specific time choosen by the user.
Eg: let say user chooses plot for 10 sec. Then i need to plot graph for 10 sec on x axis and the data on y axis.Thanks

**Comment by vishnucool220** [comment]
I tried adding data to the graph like this:
plot.addPoints(2,4)
 and i got the error
TypeError: Property 'reduceRight' of object 4 is not a function. Can you please throw some example where  i can add the data at run time. for example i get the data from Cpp side throught a signal to QML side now how can i apped the data and plot it for specific time choosen by the user.
Eg: let say user chooses plot for 10 sec. Then i need to plot graph for 10 sec on x axis and the data on y axis.Thanks

**Comment by ncp1402** [comment]
1st setup graph(s): to add graph call addGraph(name,visible,color,width,style)
to add point(s) call  plot.addPoints(x, [y1,y2,...])
y - is array of Y coordinates.

**Comment by vishnucool220** [comment]
Yeah i have done as you said but still no result.
```
property var names: ['T1']
 Component.onCompleted: {
            // add new graphs
            //            for (var i=0; i < colors.length; i++)
            addGraph(names[0], true, colors[0], 1, 'solid');
            var y = [3,4,5,6,7]
            addPoints(x,y)
        }
```
i even tried varies values of x but still no result.May i know what wrong am i doing?

**Comment by vishnucool220** [comment]
Is it possible to show me your code the picture you have show as an example . where you have added some data.

**Comment by ncp1402** [comment]
addPoints adds points for all graphs, for single X coordinate.
Since You have only one graph, the right sequence is:

addPoints(0,[3]);
addPoints(1,[4]);
addPoints(2,[5]);
addPoints(3,[6]);
addPoints(4,[6]);

**Comment by vishnucool220** [comment]
Thanks a lot. now i understood. how it works.
