### ISSUE TITLE
 TypeError: Property 'reduceRight' of object 0 is not a function

### ISSUE THREAD

**Issue by FranciscMoldovan** [ncp1402/ql-lineplot#12]
Hi! 
I just can't figure out why qml keeps giving the error mentioned in the title.
QlLinePlot.qm:130

`function addPoints(x,y){
		plot.addPoints(x,y);
		dataXY.push({'x':x, 'y':y,
			'yMin':y.reduceRight(function(prev,cur){ return isNaN(cur) ? prev : (cur < prev) ? cur : prev; }, Infinity),
			'yMax':y.reduceRight(function(prev,cur){ return isNaN(cur) ? prev : (cur > prev) ? cur : prev; }, -Infinity),
		});
		xPrev = x; // remember previous X,Y
		yPrev = y;
	}`

Could you please help me out? Thanks!

**Comment by ncp1402** [comment]
y must be array, not number

**Comment by FranciscMoldovan** [comment]
Thanks for the quick answer!
