### ISSUE TITLE
not able to draw boundary

### ISSUE THREAD

**Issue by vishnucool220** [ncp1402/ql-lineplot#4]
Hi,
I have points in an array. when plot thoes points it should plot and coundary looks like a circular ground. But instaed of that I get peaks its because the lines are drawn between the adjacent points not as the order i specified .Can you please tell me how to draw lines between points as the order i specified. Thanks

    property var logicalValue_x: [-80,-40,40,80,220,400,740,680,170,-170,-250,-220,-80,-40,-20,-80]
    property var logicalValue_z: [820,820,820,820,780,670,560,305,295,285,380,780,820,820,820,820]
    for(var i=0;i<7;i++){
                    plot.addPoints(logicalValue_x[i],[logicalValue_z[i]]);
                }

**Comment by ncp1402** [comment]
please take screenshot of what You mean...

**Comment by vishnucool220** [comment]
https://app.box.com/s/0a01or2w7acejja5r32ncm9b9mhg3eny

Here it is.

**Comment by vishnucool220** [comment]
hi, sorry to bother you again. 
Can you throw some hints on how to draw this kind of graph https://app.box.com/s/0a01or2w7acejja5r32ncm9b9mhg3eny ? Thanks

**Comment by ncp1402** [comment]
in qcustomplot ? don't know... at the worst, you can draw on canvas.

**Comment by vishnucool220** [comment]
okay.Thanks
