### ISSUE TITLE
How to update Xrange on runtime?

### ISSUE THREAD

**Issue by vishnucool220** [ncp1402/ql-lineplot#8]
Hello,
I have been using work for quite long time. Thanks a lot. 
Can you please help me, how change the xrange while adding the data at the same time. 
What exactly i need to plot is only the last 10sec over the time. 
i.e X range has to be updated every sec from min t to max t+10;
I have done like this:
if(secondsElapsed > 10)
        {
            xRangeMinValue = secondsElapsed-10;            
            plot.setRangeX(xRangeMinValue,secondsElapsed);// so the difference between xmin and xmanx is 10;
            plot.replot();
        }
plot.addPoints(secondsElapsed,[currentX,currentY]);// At this point xrangemin is reset to zero i don't know why. 
Can you help me how to change x range even if add a new data. 
The graph is always ploting from zero. Thanks

**Comment by ncp1402** [comment]
try to disable autorange plot.setAutoRange(false)

**Comment by vishnucool220** [comment]
perfect. Thanks a lot
