### ISSUE TITLE
How to plot as 2 series?

### ISSUE THREAD

**Issue by vishnucool220** [ncp1402/ql-lineplot#9]
Hello @ncp1402 
I would like to plot 2 seriers graph. I mean single line graph but with different color/representation. 
Eg like this: 
![2seriesgraph](https://cloud.githubusercontent.com/assets/7951522/12815637/e3013596-cb47-11e5-8402-5aae9793b07f.PNG).
Can you please help in ploting like that. Thanks

**Comment by ncp1402** [comment]
create 2 plots with different styles.

**Comment by vishnucool220** [comment]
I didn't get you exatly. 
are you saying to create 2 separate plots or graps
i.e 2 QlLinePlot { id:plot}

or
  addGraph(names[i], true, colors[i], 1, 'solid');
if so how to add data points to both of them?

**Comment by ncp1402** [comment]
create 1 plot with 2 graphs:

```javascript
addGraph('Actual', true, "blue", 2, 'solid');
addGraph('Future', true, "blue", 1, 'dash');
```

Then add points, for future points on Actual graph add NaNs:

```javascript
addPoints(0, [0.3,NaN]); // Actual points visible, Future invisible
addPoints(1, [0.1,NaN]);
addPoints(2, [0.6,NaN]);
addPoints(3, [NaN,0.9]); // Actual points invisible, Future visible
addPoints(4, [NaN,0.2]);
addPoints(5, [NaN,0.7]);
```

**Comment by vishnucool220** [comment]
wow ! Perfect Thanks a lot :+1:
